name: Sync to GitLab

on:
  push:
    branches:
      - main  # or change to your default branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Push to GitLab
        run: |
          git config --global user.email "varadpensalwar@gmail.com.com"
          git config --global user.name "Varad Pensalwar"
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/varadpensalwar/docmind.git
          git push gitlab main --force
